services:
  gossip-app:
    image: ghcr.io/skiesgames/gossipapp:latest
    pull_policy: always
    restart: unless-stopped
    network_mode: host
    environment:
      MODE: ${MODE}
      COORDINATOR_IP: ${COORDINATOR_IP}
      COORDINATOR_PORT: ${COORDINATOR_PORT}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
    volumes:
      - ./logs:/app/logs

#
# GossipApp Single Container Setup:
# - Each VPS runs one container with different environment variables
# - VPS 1: MODE=server (Coordinator)
# - VPS 2: MODE=client (Client 1)
# - VPS 3: MODE=client (Client 2)
# - Uses host networking mode for simplicity
# - Healthcheck only works for server (coordinator)
# - Logs are persisted to host filesystem
# - Environment variables control the application behavior:
#   - MODE: Determines application mode (server/client)
#   - COORDINATOR_IP/PORT: Network configuration (only needed for clients)
#   - TELEGRAM_BOT_TOKEN/CHAT_ID: Telegram integration (only needed for server)
