# deploy.yml
---
- name: Deploy/Update GossipApp
  hosts: all
  become: true
  tasks:
    - name: Sync updated repo files to VPS
      ansible.posix.synchronize:
        src: "{{ playbook_dir }}/../../"  # Sync entire repo
        dest: /opt/gossipapp/
        delete: yes
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=logs"

    - name: Regenerate .env file based on VPS role
      ansible.builtin.copy:
        dest: /opt/gossipapp/.env
        content: |
          IS_SERVER={{ lookup('env', 'IS_SERVER') | default('false') }}
          IS_CLIENT={{ lookup('env', 'IS_CLIENT') | default('false') }}
          COORDINATOR_IP={{ lookup('env', 'COORDINATOR_IP') | default(ansible_host) }}
          COORDINATOR_PORT={{ lookup('env', 'COORDINATOR_PORT') | default('8888') }}
          TELEGRAM_BOT_TOKEN={{ lookup('env', 'TELEGRAM_BOT_TOKEN') }}
          TELEGRAM_CHAT_ID={{ lookup('env', 'TELEGRAM_CHAT_ID') }}
        mode: '0600'

    - name: Deploy with force recreate
      community.docker.docker_compose_v2:
        project_src: /opt/gossipapp
        state: present
        recreate: always
        remove_orphans: true
        wait: true
        wait_timeout: 30
